# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#


development:
  adapter: mysql2
  encoding: utf8
  database: pwn_development
  username: root
  password: password2
  host: localhost


# Add the below...

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: test1_production
  password: password4

